# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\settingsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Settings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Settings)
        self.tabWidget.setObjectName("tabWidget")
        self.main_tab = QtWidgets.QWidget()
        self.main_tab.setObjectName("main_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lang_groupBox = QtWidgets.QGroupBox(self.main_tab)
        self.lang_groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lang_groupBox.setFlat(False)
        self.lang_groupBox.setCheckable(False)
        self.lang_groupBox.setObjectName("lang_groupBox")
        self.formlayout = QtWidgets.QFormLayout(self.lang_groupBox)
        self.formlayout.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formlayout.setObjectName("formlayout")
        self.lang_label = QtWidgets.QLabel(self.lang_groupBox)
        self.lang_label.setObjectName("lang_label")
        self.formlayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lang_label)
        self.lang_comboBox = QtWidgets.QComboBox(self.lang_groupBox)
        self.lang_comboBox.setObjectName("lang_comboBox")
        self.formlayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lang_comboBox)
        self.verticalLayout_2.addWidget(self.lang_groupBox)
        self.style_groupBox = QtWidgets.QGroupBox(self.main_tab)
        self.style_groupBox.setObjectName("style_groupBox")
        self._2 = QtWidgets.QFormLayout(self.style_groupBox)
        self._2.setHorizontalSpacing(9)
        self._2.setVerticalSpacing(6)
        self._2.setObjectName("_2")
        self.style_label = QtWidgets.QLabel(self.style_groupBox)
        self.style_label.setObjectName("style_label")
        self._2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.style_label)
        self.style_comboBox = QtWidgets.QComboBox(self.style_groupBox)
        self.style_comboBox.setObjectName("style_comboBox")
        self._2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.style_comboBox)
        self.font_size_spinBox = QtWidgets.QSpinBox(self.style_groupBox)
        self.font_size_spinBox.setMinimum(9)
        self.font_size_spinBox.setMaximum(20)
        self.font_size_spinBox.setProperty("value", 9)
        self.font_size_spinBox.setObjectName("font_size_spinBox")
        self._2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.font_size_spinBox)
        self.fontsize_label = QtWidgets.QLabel(self.style_groupBox)
        self.fontsize_label.setObjectName("fontsize_label")
        self._2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.fontsize_label)
        self.verticalLayout_2.addWidget(self.style_groupBox)
        self.tabWidget.addTab(self.main_tab, "")
        self.path_tab = QtWidgets.QWidget()
        self.path_tab.setObjectName("path_tab")
        self.tabWidget.addTab(self.path_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(Settings)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.lang_label.setBuddy(self.lang_comboBox)
        self.style_label.setBuddy(self.style_comboBox)

        self.retranslateUi(Settings)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Settings.accept) # type: ignore
        self.buttonBox.rejected.connect(Settings.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Settings"))
        self.lang_groupBox.setTitle(_translate("Settings", "Language"))
        self.lang_label.setText(_translate("Settings", "Languages"))
        self.style_groupBox.setTitle(_translate("Settings", "Appereances"))
        self.style_label.setText(_translate("Settings", "Styles"))
        self.fontsize_label.setText(_translate("Settings", "Font Size"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.main_tab), _translate("Settings", "General"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.path_tab), _translate("Settings", "Paths"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Settings = QtWidgets.QDialog()
    ui = Ui_Settings()
    ui.setupUi(Settings)
    Settings.show()
    sys.exit(app.exec_())
