name: Build Marmara Connector

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_Debian:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.6"
      - name: Install python dependencies
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends libcurl4-openssl-dev libssl-dev python3-dev python3 python3-pip python3-venv qttools5-dev-tools python3-pyqt5
          python3 -m venv venv
          source venv/bin/activate
          sudo apt-get install ruby ruby-dev rubygems build-essential
          sudo gem install --no-document fpm
          fpm --version    
          pip install pip -U
          pip install wheel
          pip install -r requirements.txt
          fbs freeze
          fbs installer
      - name: Upload a Build Artifact (Linux AppImage)
        uses: actions/upload-artifact@v2.3.1
        with:
          retention-days: 7
      
      - name: Upload a Build Artifact (Linux ZIP)
        uses: actions/upload-artifact@v2.3.1
        with:
          retention-days: 7
